{"name": "test_login3", "status": "failed", "statusDetails": {"message": "AssertionError: assert 0", "trace": "self = <script.test_login.TestLogin object at 0x0000000003942320>\n\n    def test_login3(self):\n>       assert 0\nE       assert 0\n\nscript\\test_login.py:10: AssertionError"}, "start": 1601886819416, "stop": 1601886819417, "uuid": "7586caa6-94be-44d8-8339-b9e27430d73b", "historyId": "75dfddf0dcc92fb23551e5da50e8f9bf", "testCaseId": "b7a4b0d8149ddf7881c367f491382e52", "fullName": "script.test_login.TestLogin#test_login3", "labels": [{"name": "parentSuite", "value": "script"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "SKY-20171211NJY"}, {"name": "thread", "value": "6608-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "script.test_login"}]}